name: Release Jar

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build fat jar
        run: ./gradlew :shadowJar
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/meal-planner.jar"
          body: |
            Release meal planner
